### PR TITLE
Add ru lang

### PR DESCRIPTION
**Pull request by T0pN1ck**

### CODE REVIEW

**Comment by 62832** [comment]
Can't merge just yet since I need to come back to this one and ask for a translation for the new cable part being introduced in #79.

**Comment by T0pN1ck** [comment]
> Can't merge just yet since I need to come back to this one and ask for a translation for the new cable part being introduced in #79.

Kk, pending completion of work

**Comment by 62832** [comment]
Cell Dock has been merged now, happy to merge this once a translation key has been included for it.

**Comment by T0pN1ck** [comment]
Well, now it's ready to merge

**Pull request merged**
