### PR TITLE
Add ru lang

### PR DESCRIPTION
**Pull request by T0pN1ck**

### CODE REVIEW

**Comment by 62832** [comment]
Thanks for the contribution. I would ask, however, if there is any possible Russian translation of the MEGA / ME Greater Accumulation prefix as opposed to just "ME".

**Comment by T0pN1ck** [comment]
ofc, its just that the translation was originally intended to preserve the originality to ae2

**Comment by 62832** [comment]
I just noticed, this is targeting the 1.19 branch. I would really prefer if PRs targeted the current master branch (1.20).

**Comment by T0pN1ck** [comment]
omg, how its works in 1.20...

I will send pull request tomorrow after I get a more detailed look at it.

**Comment by 62832** [comment]
The data generator only covers `en_us`, so you should still be able to submit a translation just fine.

**Pull request merged**
